### ISSUE TITLE
[Bug] 无法访问 store 链接

### ISSUE THREAD

**Issue by yi-Xu-0100** [Richasy/LoopbackManager.Desktop#2]
### Bug description / Bug 描述

readme 中的 `ms-windows-store://pdp/?productid=9NTJ6CX698CL` 没法跳转到 store

### Reproduce steps / 复现问题的步骤

```plain text
如 readme 所示，复制链接到浏览器，跳转后显示找不到页面
```

### Expected behavior / 预期行为

找到页面能够通过 store 找到安装

### Screenshot / 截图

![image](https://user-images.githubusercontent.com/25523606/180905182-1f485405-8200-43d2-ac61-353718b78c01.png)

### Application source / 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] Others / 其它

### System version

- [ ] Windows 11 21H2 (Build 22000)
- [X] Others / 其它

### Other system versions / 其它系统版本

Windows 11 22621

### Device / 运行设备

Desktop/桌面/台式机

**Comment by Richasy** [comment]
还没过审……开源开早了😂

**Comment by Richasy** [comment]
已经上线，关闭此issue
